### PR TITLE
Bugzilla1968: Refactored Rule.

### PR DESCRIPTION
**Pull request by marktrayer**

### CODE REVIEW

**Comment by AndreMaz** [comment]
Hi @marktrayer 
Is there any public docs about the `ruleexpression` syntax? Where can I find the actual BNF? The only reference that I'm aware of is in [mjkoster's draft](https://github.com/mjkoster/ocf-working/blob/master/docs/CR%20ATG%201968%20Rules.docx)

**Comment by marktrayer** [comment]
@AndreMaz the BNF that is in the link is actually taken (mostly) from the CDS search BNF defined by UPnP.  Either way the expression syntax is the same with some additional clarity provided on how a resourceproperty is indicated.

**Comment by marktrayer** [comment]
PR and branch have been moved to core-extensions.

**Comment by AndreMaz** [comment]
Thanks @marktrayer :+1: 
One more thing, do you have any time window for Rule to be merged? I mean, Rule PRs have been sitting here for quite a while.

**Pull request closed without merging**
