### PR TITLE
 BZ3260-Sleepy-nodes Update oic.links.properties.core-schema.json

### PR DESCRIPTION
**Pull request by WAvdBeek**

### CODE REVIEW

**Review by marktrayer — COMMENTED** [review]
Just verifying, is "lat: 0 a valid population for this Property?  Or is the real minimum value "lat": 1?

**Comment by WAvdBeek** [comment]
it is not including exclusiveMinimum, so the actual minimal value > 0.

practical, i do not know how to implement this with latency=0.

**Comment by marktrayer** [comment]
Thought it was the other way around; if using draft 4 then the validation spec is: https://tools.ietf.org/html/draft-fge-json-schema-validation-00#page-7 which defines "minimum" without "exclusiveMinimum" as "greater than or equal to".  So a value of "0" would be valid; which I confirmed also using the Newton Soft online validator.  

If we did want to allow a value of "0" we could define that as "infinite" meaning there is not timeout on waiting for a response.  This probably is also impractical to implement though.

**Comment by WAvdBeek** [comment]
i can add exclusiveMinimum, that is better than identifying 0 as infinitive
let me know...

**Comment by marktrayer** [comment]
That works for me!

**Comment by WAvdBeek** [comment]
added exclusiveMinimum as JSON draft04

**Pull request merged**
